import type { WeaveworkerData } from '@/domain/models';

export const createDemoDataset = (): WeaveworkerData => {
  const now = new Date().toISOString();

  return {
    account: {
      id: 'account-001',
      profile: {
        id: 'profile-001',
        name: 'Jordan Lee',
        email: 'jordan@weaveworker.dev',
      },
      teamIds: ['team-001'],
      localSettings: {
        theme: 'dark',
        offlineMode: true,
        featureFlags: ['marketplace-preview'],
      },
      vaultRefs: {
        n8nApiKeyRef: 'vault:n8n:key',
        aiKeyRefs: ['vault:openai:key'],
      },
      entitlementsId: 'entitlements-001',
    },
    teams: [
      {
        id: 'team-001',
        name: 'Weaveworker HQ',
        members: [
          { profileId: 'profile-001', role: 'owner' },
          { profileId: 'profile-002', role: 'admin' },
        ],
        policy: {
          approvalsRequired: true,
          runLimitsPerDay: 120,
          allowedIntegrations: ['n8n', 'slack', 'gmail'],
        },
        projectIds: ['project-001', 'project-002'],
        workerIds: ['worker-001', 'worker-002'],
        assetIds: ['asset-001', 'asset-002'],
        flowIds: ['flow-001'],
      },
    ],
    projects: [
      {
        id: 'project-001',
        name: 'Customer Success Ops',
        description: 'Automations for onboarding, follow-ups, and renewals.',
        status: 'active',
        memberRoles: [
          { profileId: 'profile-001', role: 'owner' },
          { profileId: 'profile-002', role: 'admin' },
        ],
        workerIds: ['worker-001'],
        assetIds: ['asset-001'],
        taskIds: ['task-001'],
        flowIds: ['flow-001'],
        operationIds: ['operation-001'],
      },
      {
        id: 'project-002',
        name: 'Marketing Pipeline',
        description: 'Content and outreach workflows for the next campaign.',
        status: 'active',
        memberRoles: [{ profileId: 'profile-001', role: 'owner' }],
        workerIds: ['worker-002'],
        assetIds: ['asset-002'],
        taskIds: ['task-002'],
        flowIds: [],
        operationIds: [],
      },
    ],
    workers: [
      {
        id: 'worker-001',
        title: 'Lifecycle Specialist',
        jobDescription: 'Designs customer success playbooks and retention ops.',
        persona: 'Warm, data-driven operator focused on health scores.',
        sops: ['Renewal outreach', 'Onboarding handoff'],
        toolPolicy: 'Requires approval to send emails externally.',
        assignedProjectIds: ['project-001'],
        memory: {
          retentionDays: 90,
          rememberAssets: true,
          rememberThreads: true,
        },
        threadIds: ['thread-001'],
        knowledgeAssetIds: ['asset-001'],
      },
      {
        id: 'worker-002',
        title: 'Campaign Producer',
        jobDescription: 'Builds multi-channel marketing campaigns.',
        persona: 'Energetic strategist with strong copywriting skills.',
        sops: ['Weekly campaign planning', 'Social content calendar'],
        toolPolicy: 'Drafts content, requires review before publish.',
        assignedProjectIds: ['project-002'],
        memory: {
          retentionDays: 60,
          rememberAssets: true,
          rememberThreads: true,
        },
        threadIds: ['thread-002'],
        knowledgeAssetIds: ['asset-002'],
      },
    ],
    assets: [
      {
        id: 'asset-001',
        type: 'doc',
        title: 'Onboarding Playbook',
        content: 'Step-by-step onboarding sequence with checkpoints.',
        tags: ['onboarding', 'success'],
        source: 'Notion',
        createdBy: 'profile-001',
        permissions: ['owner', 'admin', 'member'],
        embeddingStatus: 'ready',
        summary: 'Core onboarding steps and health score triggers.',
      },
      {
        id: 'asset-002',
        type: 'note',
        title: 'Q4 Campaign Brief',
        content: 'Launch plan for Q4 automation campaign.',
        tags: ['marketing', 'campaign'],
        source: 'Local Note',
        createdBy: 'profile-001',
        permissions: ['owner', 'admin', 'member'],
        embeddingStatus: 'pending',
        summary: 'Campaign goals, channels, and CTA drafts.',
      },
    ],
    threads: [
      {
        id: 'thread-001',
        workerId: 'worker-001',
        projectId: 'project-001',
        messages: [
          {
            id: 'message-001',
            role: 'user',
            content: 'Draft a renewal outreach sequence for mid-market.',
            timestamp: now,
          },
        ],
        artifacts: {
          summaries: ['Renewal sequence drafted with 3 steps.'],
          decisions: ['Require approval before sending to live customers.'],
          actionItems: ['Review sequence copy and approve.'],
        },
      },
      {
        id: 'thread-002',
        workerId: 'worker-002',
        projectId: 'project-002',
        messages: [
          {
            id: 'message-002',
            role: 'user',
            content: 'Outline weekly social posts for the launch.',
            timestamp: now,
          },
        ],
        artifacts: {
          summaries: ['Outlined 5 weekly content themes.'],
          decisions: ['Prioritize LinkedIn and newsletter.'],
          actionItems: ['Assign copy to Campaign Producer.'],
        },
      },
    ],
    tasks: [
      {
        id: 'task-001',
        title: 'Finalize renewal email copy',
        description: 'Prepare the final draft and route for approval.',
        status: 'needs_review',
        assigneeId: 'worker-001',
        dueDate: now,
        priority: 'high',
        linkedAssetIds: ['asset-001'],
        linkedThreadIds: ['thread-001'],
        linkedOperationIds: ['operation-001'],
      },
      {
        id: 'task-002',
        title: 'Build Q4 campaign calendar',
        description: 'Create a 6-week schedule with channels.',
        status: 'assigned',
        assigneeId: 'worker-002',
        dueDate: now,
        priority: 'medium',
        linkedAssetIds: ['asset-002'],
        linkedThreadIds: ['thread-002'],
        linkedOperationIds: [],
      },
    ],
    flows: [
      {
        id: 'flow-001',
        name: 'Renewal Outreach Flow',
        description: 'n8n workflow to send renewal sequences with approvals.',
        n8nWorkflowJson: '{"nodes": [], "connections": {}}',
        triggers: ['manual', 'schedule:0 9 * * 1'],
        inputsSchema: '{"type":"object","properties":{"accountId":{"type":"string"}}}',
        requiresApproval: true,
        version: 3,
      },
    ],
    operations: [
      {
        id: 'operation-001',
        flowId: 'flow-001',
        triggeredBy: 'profile-001',
        status: 'succeeded',
        startedAt: now,
        finishedAt: now,
        logs: ['Queued run', 'Awaiting approval', 'Approved by owner', 'Run succeeded'],
        outputs: ['Emails queued for 42 accounts'],
        artifacts: ['artifact:renewal-summary.pdf'],
        costUsd: 3.21,
      },
    ],
    integrations: [
      {
        id: 'integration-001',
        type: 'n8n',
        name: 'n8n Cloud',
        baseUrl: 'https://n8n.example.com',
        authMethod: 'api_key',
        instanceId: 'n8n-cloud-001',
        secretRef: 'vault:n8n:key',
      },
    ],
    auditEvents: [
      {
        id: 'audit-001',
        timestamp: now,
        actorId: 'profile-001',
        action: 'flow.run.approved',
        targetType: 'flow',
        targetId: 'flow-001',
        metadata: { project: 'Customer Success Ops' },
      },
    ],
    entitlements: {
      id: 'entitlements-001',
      tier: 'pro',
      seats: 10,
      projectsLimit: 50,
      workersLimit: 50,
      operationsPerDay: 500,
      retentionDays: 365,
      features: ['teams', 'sync', 'approvals', 'scheduler', 'marketplace'],
    },
  };
};
